plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bio.games'
    compileSdk 34

    defaultConfig {
        applicationId "com.bio.games"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField "boolean", "ENABLE_SECURITY_CHECKS", "true"
        }
        debug {
            buildConfigField "boolean", "ENABLE_SECURITY_CHECKS", "false"
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}